# versionはComposeファイルのバージョンでありDocker Compose自体のバージョンとは異なることに注意
version: '3.8'

volumes:
  mysql-volume:

services:
  # サービス名: PHP
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./src/:/var/www/test/
    # 環境変数を設定(.envに紐づく)
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=test
      - DB_USERNAME=tester
      - DB_PASSWORD=tester

  # サービス名: Nginx
  web:
    # ビルドするDockerfileの指定
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    # ローカル(PC)とDockerコンテナ間のポート番号の対応づけを設定{ローカル}:{Dockerコンテナ}
    ports:
      - ${WEB_PORT}:80
    # コンテナ間の依存関係を設定(appはPHPアプリケーションのコンテナを指す)PHP->Nginxの順にコンテナを起動させる
    depends_on:
      - app
    # ローカルとDockerコンテナ間のディレクトリ・ファイル等のリソースを対応づける設定(ローカルのリソース:Dockerコンテナ内のリソース)
    volumes:
      - ./src/:/var/www/test/

  # サービス名: MySQL
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    # ローカルのポート番号(MySQLのデフォルトのポート番号は3306)
    ports:
      - ${DB_PORT}:3306
    # MySQLの環境変数
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: tester
      MYSQL_PASSWORD: tester
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
